name: pnhs_go
description: "A Flutter project to demonstrate naviagtion within Pontevedra National High School"
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.3.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  random_avatar: ^0.0.8
  flutter_mapbox_navigation: ^0.2.2
  shared_preferences: ^2.2.3
  dio: ^5.4.3+1
  mapbox_maps_flutter: ^0.4.4
  intl: ^0.19.0
  google_fonts: ^6.2.1
  flutter_native_splash: ^2.2.16
  flutter_dotenv: ^5.1.0
  ionicons: ^0.2.2
  firebase_core: ^2.30.1
  firebase_auth: ^4.19.4
  cloud_firestore: ^4.17.2
  google_sign_in: ^6.2.1
  geolocator: ^11.0.0
  shimmer: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/icon/
    - assets/image/
    - assets/config/
